- name: run all benchmarks and capture db logs
  shell: |
    {{ansible_env.HOME}}/bench-tool benchmark\
      --chain dev\
      --execution=wasm\
      --wasm-execution=compiled\
      --pallet {{item.pallet}}\
      --extrinsic {{item.extrinsic}}\
      --raw\
      --steps {{benchmark_steps}}\
      --repeat {{benchmark_repeat}}\
      > {{ansible_env.HOME}}/results/{{item.pallet}}.{{item.extrinsic}}.txt

    # capture db logs
    {{ansible_env.HOME}}/bench-tool benchmark\
      --chain dev\
      --execution=wasm\
      --wasm-execution=compiled\
      --pallet {{item.pallet}}\
      --extrinsic {{item.extrinsic}}\
      --steps {{benchmark_steps}}\
      --log state-trace=trace,benchmark=trace\
      2> {{ansible_env.HOME}}/results/{{item.pallet}}.{{item.extrinsic}}.log
  vars:
    temp: "{{ lookup('file', 'temp.json') }}"
  loop: '{{ temp }}'
  async: 0
  poll: 60
