- name: run limited (balances & staking) benchmarks
  shell: |
    {{ansible_env.HOME}}/bench-tool benchmark\
      --chain dev\
      --execution=wasm\
      --wasm-execution=compiled\
      --pallet {{item[0]}}\
      --extrinsic {{item[1]}}\
      --raw\
      --steps {{benchmark_steps}}\
      --repeat {{benchmark_repeat}}\
      > {{ansible_env.HOME}}/results/{{item[0]}}.{{item[1]}}.txt

    # capture db logs
    {{ansible_env.HOME}}/bench-tool benchmark\
      --chain dev\
      --execution=wasm\
      --wasm-execution=compiled\
      --pallet {{item[0]}}\
      --extrinsic {{item[1]}}\
      --steps {{benchmark_steps}}\
      --log state-trace=trace,benchmark=trace\
      2> {{ansible_env.HOME}}/results/{{item[0]}}.{{item[1]}}.log
  with_nested:
    - '{{balances_benchmarks|
      union(staking_benchmarks)}}'
  async: 0
  poll: 60
