---
- name: Converge
  hosts: all
  tasks:
    - name: "Include substrate-benchmarks-role"
      include_role:
        name: "substrate-benchmarks-role"
      vars:
        scope: limited
        steps: 1
        repeat: 1
