---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: 'polkadot-module-benchmarks'
    image: ubuntu:19.10
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
  # - idempotence    
    - lint
    - verify
verifier:
  name: ansible
