name: Build substrate with runtime-benchmarks feature enabled and publish as release

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - 'trigger-actions'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Clone substrate repo
      uses: actions/checkout@v2
      with:
        repository: paritytech/substrate
        path: substrate

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('substrate/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('substrate/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: substrate/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('substrate/Cargo.lock') }}

    - name: Prepare environment
      run: |
        curl https://getsubstrate.io -sSf | bash -s -- --fast
        source ~/.cargo/env
        sudo apt-get update && sudo apt-get install python3

    - name: Build substrate with runtime-benchmarks feature enabled
      run: |
        cargo build -p node-cli --release --features=runtime-benchmarks
        cargo build -p node-bench --release

    - name: Checkout local repo for parsing tool
      uses: actions/checkout@v2
      with:
        path: main

    - name: Parse substrate output to JSON format (list of available benchmarks)
      run: |
        ./substrate/target/release/substrate benchmark --pallet "*" --extrinsic "*" --steps 0 > dump.txt
        python3 main/.github/tools/parse_benches.py dump.txt > module_benchmarks.json

    - name: Upload node-cli to Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: substrate/target/release/substrate
        asset_name: substrate
        tag: assets
        overwrite: true

    - name: Upload node-bench to Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: substrate/target/release/node-bench
        asset_name: node-bench
        tag: assets
        overwrite: true

    - name: Upload JSON list of available benchmarks to Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: module_benchmarks.json
        asset_name: module_benchmarks.json
        tag: assets
        overwrite: true
